Connect redux react
MarkoKermi/bookstore_react_project pull request #3
Opened 2023-03-01 17:38 UTC by MarkoKermi

- [ ] Display your books, received from the slice, in a reusable component
- [ ] Dispatch actions using useDispatch

- [ ] Add a <Button> component, which includes:
An event handler that adds a book to the books array (with attributes id, title and author)

- [ ] Add a <Button> component, which includes:
An event handler that removes a book from the books array (by id)

- [ ] Add a <Button> component, which includes:
An event handler that check status (i.e add a functionality for "Check status" button click)

2023-03-01 18:20 UTC, pinkmoon25 requested changes
Hi @MarkoKermi , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media1.giphy.com/media/KyBesf8kNT6s88SEgb/giphy.gif"/>

## Highlights
linter checks :heavy_check_mark: 
gitflow :heavy_check_mark: 
react-redux :heavy_check_mark: 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-01 18:20 UTC, pinkmoon25 commented on src/components/Book.js
> +    // console.log(bookstore);
- [ ] Please also remove this commented code, as mentioned in the best practices we do not commit commented code in the codebase, makes things cluttered :+1:

2023-03-01 18:20 UTC, pinkmoon25 commented on src/components/Categories.js
> +  const Categories = useSelector(({ category }) => category.categories);
- [ ] hi @MarkoKermi you have done really well connecting redux, there is one small issue though, when we try to go to the categories page we get these errors :point_down: 
![image](https://user-images.githubusercontent.com/97521557/222227021-8a8b93a3-c9a7-46e6-a7a0-d27b731f1b13.png)

this is because you have named your categoriesReducer as categories and not category, and you are trying to get the state value using category instead of categories 
see your store :point_down: 
```
const store = configureStore({
  reducer: {
    books: booksReducer,
    categories: categoriesReducer,
  },
});
```

2023-03-02 09:25 UTC, OyePriscilla requested changes
Hi @MarkoKermi 👏, 

Great work on making the changes requested by a previous reviewer 👏 

You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![so-close-so-close-seth-meyers](https://user-images.githubusercontent.com/103386183/196425724-8ca5825c-b02a-4983-b976-4bd0a2f70f9a.gif)

 ## Highlights
Use store, actions and reducers in React ✔️ 
Connect React and Redux ✔️ 
Categories page accessible ✔️  

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

- [optional] Please kindly update the future feature and live demo (if there is no live demo, kindly indicate 'Not yet Available') sections of the README file. I observed that the MIT license is broken as well, please fix all these for your repo to look professional. 👍 

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-02 09:25 UTC, OyePriscilla commented on src/components/Book.js
> +  };
- [ ] Please try and remove the commented code as raised earlier, this will make your codebase clean according to the best practises. :info

2023-03-02 09:44 UTC, christianbiring1 approved these changes
Hi @MarkoKermi , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
# STATUS: APPROVED :tada: 
![nicee](https://user-images.githubusercontent.com/97100091/222391075-8a50b0ef-c57a-47e8-9f5b-0392740177d0.gif)

## Highlights
- [ ] All linters checks are green :heavy_check_mark: 
- [ ] Descriptive PR `title` and `summary` :+1: 
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-02 09:45 UTC, merged